### ISSUE TITLE
C++ code for OMG project

### ISSUE THREAD

**Issue by yungyuc** [LittleLaGi/OhMyGene#4]
It has not been clear to me how you will divide the high-performance C++ code from high-level controlling Python code, because you have not added C++ code for the OMG project.  Could you start adding C++ code?

You already have automatic testing.  It will improve coding productivity to have CI set up.

**Comment by LittleLaGi** [comment]
During the development, I found out I misunderstood some GA concepts, so I create another branch: RWGA to hold most of my C++ code. Most of the features have been finished, I'll move the code to the main branch soon.

**Comment by yungyuc** [comment]
Thanks for pointing it out.  This is another reason why adding CI helps.  If CI were there, a visitor can inspect the GithubAction log to learn what you are doing in thte active branch `RWGA` and save time in reviewing all the branches.

I see your C++ code and it looks OK to me.  It looks simple enough to work without a namespace.  If you plan to grow it to be 10x larger, you may consider to give your code a dedicated namespace to reduce the odds of name collision in the global namespace.

**Comment by LittleLaGi** [comment]
Thanks for the advice!
I'm not used to developing this kind of project, GA itself has bothered me for a while.

**Comment by yungyuc** [comment]
I believe none of the class is used to develop projects that involve numerical methods like this.  In fact, it is the point to develop something we are not familiar with.  That is what makes programming fun.  You will _experience_ the process in the term project and learn that you have to change how you think about programming.  I hope you also learn how to use discussions to help you code, too.
